version: 2.1


jobs:
  print_hello:
    environment:
      hello_message: Hello
    docker:
      - image: circleci/node:13.8.0
    steps:
    - run:
        name: printing hello
        command: |
          echo $hello_message

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

  print_my_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo my name is $MY_NAME

  save_print_helloworled:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Hello Worled! >> output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  load_print_helloworled:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat output.txt
workflows:
  Main:
    jobs:
      - save_print_helloworled
      - load_print_helloworled:
          requires:
            - save_print_helloworled



