version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create cloud formation stack
          command: |
            aws cloudformation deploy --template-file template.yml  --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} 


workflows:
  Main:
    jobs:
      - create_infrastructure



