version: 2.1


jobs:
  print_hello:
    environment:
      hello_message: Hello
    docker:
      - image: circleci/node:13.8.0
    steps:
    - run:
        name: printing hello
        command: |
          echo $hello_message

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world


workflows:
  Main:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello



