version: 2.1

environment:
  hello_message: Hello
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
    - run: 
      name: prining hello
      command: |
        echo $hello_message

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world


workflows:
  Main:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello



